# Generated by Django 3.0.5 on 2020-05-12 14:29

import apps.errand.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('errand', '0002_errand'),
    ]

    operations = [
        migrations.AddField(
            model_name='errand',
            name='priority',
            field=enumfields.fields.EnumField(default='2', enum=apps.errand.models.Priority, max_length=1),
        ),
    ]
