# Generated by Django 3.0.5 on 2020-05-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errand', '0003_errand_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='errand',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
    ]
