# Generated by Django 3.0.5 on 2020-05-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errand', '0004_errand_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errand',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
