# Generated by Django 3.0.5 on 2020-05-18 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('errand', '0005_auto_20200513_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errand',
            options={'ordering': ('created_date',)},
        ),
    ]
