const ERRANDS_DATA = "ERRAND_DATA";
const ERRAND_BY_ID = "ERRAND_BY_ID";
const NEXT_DAYS_ERRANDS = "NEXT_DAYS_ERRANDS";
const PREVIOUS_DAYS_ERRANDS = "PREVIOUS_DAYS_ERRANDS";
const SHOW_DIALOG = "SHOW_DIALOG";
const HIDE_DIALOG = "HIDE_DIALOG";

export default {
  ERRANDS_DATA,
  ERRAND_BY_ID,
  SHOW_DIALOG,
  HIDE_DIALOG,
  NEXT_DAYS_ERRANDS,
  PREVIOUS_DAYS_ERRANDS,
};
